export enum ReasonCategory {
  PATIENT = 'PACIENTE',
  ADDRESS = 'DOMICILIO',
  PROFESSIONAL = 'PROFESIONAL',
  WEATHER = 'CLIMA',
  MEDICAL = 'MEDICO',
  PERSONAL = 'PERSONAL',
  LOGISTIC = 'LOGISTICO',
}

export enum SuggestedAction {
  RESCHEDULE = 'REPROGRAMAR',
  SUSPEND = 'SUSPENDER',
  REFER = 'DERIVAR',
  CONTACT_FAMILY = 'CONTACTAR_FAMILIA',
  VERIFY_ADDRESS = 'VERIFICAR_DOMICILIO',
}
