export enum ReasonCategory {
  PACIENTE = 'PACIENTE',
  DOMICILIO = 'DOMICILIO',
  PROFESIONAL = 'PROFESIONAL',
  CLIMA = 'CLIMA',
  MEDICO = 'MEDICO',
  PERSONAL = 'PERSONAL',
  LOGISTICO = 'LOGISTICO',
}

export enum SuggestedAction {
  REPROGRAMAR = 'REPROGRAMAR',
  SUSPENDER = 'SUSPENDER',
  DERIVAR = 'DERIVAR',
  CONTACTAR_FAMILIA = 'CONTACTAR_FAMILIA',
  VERIFICAR_DOMICILIO = 'VERIFICAR_DOMICILIO',
}
